### ISSUE TITLE
Splash is not connecting to Unsplash

### ISSUE THREAD

**Issue by cjcbusatto** [splash-cli/splash-cli#38]
#### Basic informations
- **Splash CLI** version: `3.3.2`
- Node version: `8.9.4`
- Your OS: **Windows 10**

#### Before you go
- [x] I've read the [FAQ](https://github.com/splash-cli/splash-cli/blob/master/FAQ.md) section.
- [x] I've the latest version of **Splash CLI installed**
- [x] I've searched other issues like mine but I haven't found a solution.

# The ISSUE
After the installation using `npm`, splash complains that the request is Unauthorized. 

**To Reproduce**
1. Run `splash`

**Expected behavior**
Select a random wallpaper image and change the actual wallpaper on my Desktop.

**Console Output**
```shell
OOps! We got an error!

Please report it: on GitHub (https://github.com/splash-cli/splash-cli/issues)

Splash Error:


× { HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.data (C:\Users\cbusa\AppData\Roaming\npm\node_modules\splash-cli\node_modules\got\index.js:386:13)
    at <anonymous>    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HTTPError',  host: 'api.unsplash.com',
  hostname: 'api.unsplash.com',  method: 'GET',
  path: '/photos/random?client_id=undefined&count=1&featured=false',  protocol: 'https:',
  url: 'https://api.unsplash.com/photos/random?client_id=undefined&count=1&featured=false',  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers:
   { server: 'Cowboy',
     'content-type': 'application/json',
     'access-control-allow-origin': '*',
     'access-control-request-method': '*',
     'access-control-allow-headers': '*',
     'access-control-expose-headers': 'Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining',
     'cache-control': 'no-cache',
     'x-request-id': 'f76bea16-2b99-401d-98f9-e23015425ee3',
     'x-runtime': '0.012820',
     'strict-transport-security': 'max-age=15552000',
     via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
     'accept-ranges': 'bytes, bytes, bytes, bytes',
     'content-length': '55',
     date: 'Mon, 14 Jan 2019 22:34:03 GMT',
     connection: 'close',
     'x-served-by': 'cache-iad2138-IAD, cache-gru17129-GRU',
     'x-cache': 'MISS, MISS',
     'x-cache-hits': '0, 0',
     'x-timer': 'S1547505244.562766,VS0,VE140',
     vary: 'Origin, Authorization' } }
x Unable to connect.
```

**Comment by Rawnly** [comment]
Hi 👋 

I’m sorry I know about this issue, please install v3.3.1 till fix (hopefully tomorrow morning)

**Comment by cjcbusatto** [comment]
Hi!
The version 3.3.1 works! Thanks!

**Comment by Rawnly** [comment]
Ill keep tho issue open till fix

**Comment by Rawnly** [comment]
After a little investigation i think that is a windows related problem, please check if there's a .env file inside the installation folder.

**Comment by cjcbusatto** [comment]
Yes, on 3.3.2 there is an `.env` file. 
On 3.3.1, there isn't.

**Comment by Rawnly** [comment]
it seems that in 3.3.2 it isn't loading the env variables (with the api keys), I've tested it on macOS and it's working perfectly.. I'll try to catch that in the meantime you can continue use v3.3.1

##### PR Are always welcome 👍

**Comment by Rawnly** [comment]
Hi in the meantieme you can install `3.3.3-0` that's a pre rlease till fix with all the new features of `v3.3.2`

**Comment by toby-daigle** [comment]
Hi Rawnly, i have the same problem here.
- Splash CLI version: Tested under 3.3.2 AND 3.3.3-0
- Node version: 9.10.0
- Your OS: Mac OS Mojave 10.14.2

```
OOps! We got an error!

Please report it: on GitHub (https://github.com/splash-cli/splash-cli/issues)

Splash Error:


✖ { HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.data (/Users/tdaigle/.config/yarn/global/node_modules/got/index.js:386:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
  name: 'HTTPError',
  host: 'api.unsplash.com',
  hostname: 'api.unsplash.com',
  method: 'GET',
  path: '/photos/QBrag9UhSPg?client_id=undefined',
  protocol: 'https:',
  url: 'https://api.unsplash.com/photos/QBrag9UhSPg?client_id=undefined',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers: 
   { server: 'Cowboy',
     'content-type': 'application/json',
     'access-control-allow-origin': '*',
     'access-control-request-method': '*',
     'access-control-allow-headers': '*',
     'access-control-expose-headers': 'Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining',
     'cache-control': 'no-cache',
     'x-request-id': 'ff43cbda-b509-4b60-85c5-e24632504f8f',
     'x-runtime': '0.022813',
     'strict-transport-security': 'max-age=15552000',
     via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
     'accept-ranges': 'bytes, bytes, bytes, bytes',
     'content-length': '55',
     date: 'Thu, 17 Jan 2019 13:31:11 GMT',
     connection: 'close',
     'x-served-by': 'cache-iad2141-IAD, cache-jfk8141-JFK',
     'x-cache': 'MISS, MISS',
     'x-cache-hits': '0, 0',
     'x-timer': 'S1547731872.957861,VS0,VE37',
     vary: 'Origin, Authorization' } }
✖ Unable to connect.
```

I see that in your url here, params `client_id` is undefined, not sure if that's the problem.

**Comment by Rawnly** [comment]
Hi @toby-daigle , thank you for reporting, I'll revert this change in the new patch, please in the meantime use `v3.3.3-0`

You can install it via 

```sh
yarn global add splash-cli@3.3.3-0

#or with NPM

npm i -g splash-cli@3.3.3-0
```

**Comment by hos4m** [comment]
I'm still facing this issue, I tried 3.3.3-0 and the latest version and both gave the same error.

**Comment by Rawnly** [comment]
I know guys, please have patience, I’m very very busy these days and I’m doing a big refractory for splash.

If you want to contribute you’re welcome

**Comment by Rawnly** [comment]
Btw since this version wont work you can always install `v3.2.0` or older

**Comment by Rawnly** [comment]
Can you guys install the new version **v3.3.3** and give me some feedback?

**Comment by toby-daigle** [comment]
Hi @Rawnly ! Hope you're having a good day.
Here's what i did.
`yarn global remove splash-cli`
`yarn global add splash-cli` -> which installed the 3.3.3 version, i checked.

But now i have ⚠️ `splash: Command not found`
I found out that the command `splash` has not been symlinked inside my global bin folder.
Have you changed anything in your build process ? Because when i inspected your `package.json` you specify
```
"bin": {
		"splash": "build/bin/index.js"
	},
```
but it turns out that the `build` folder here contains only a folder named `src`.
Not sure if that is the problem, hope it might help you.

- Node version: 9.10.0
- Your OS: Mac OS Mojave 10.14.3
- Yarn version: 1.13.0

**Comment by Rawnly** [comment]
Sorry, for that problem, I've released the new version without testing it (I've assumed that the guy that did the last PR has already tested it.)

I'll try to see what's changed and release an hot fix before the end of the day

**Comment by toby-daigle** [comment]
No problem buddy, take your time. I'm just here to help you:)

**Comment by jin-ds** [comment]
I still have the crash error as well. Unfortunately I'm no help with coding, I just made a Github account to report the issue.

2nd request would be to put a space after the first bracket and before the last bracket in the "Please report it: on ..." section. When you click on the link in terminal simulators, it opens the link with the bracket at the end.

-----

- node -v
v11.10.1

- splash -v
3.3.3-1

- OS
macOS 10.14.3 (18D109)

- Crash message:
```OOps! We got an error!

Please report it: on GitHub (https://github.com/splash-cli/splash-cli/issues)

Splash Error:


✖ { HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.data (/usr/local/lib/node_modules/splash-cli/node_modules/got/index.js:386:13)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  name: 'HTTPError',
  host: 'api.unsplash.com',
  hostname: 'api.unsplash.com',
  method: 'GET',
  path: '/photos/random?client_id=undefined&count=1&featured=false',
  protocol: 'https:',
  url:
   'https://api.unsplash.com/photos/random?client_id=undefined&count=1&featured=false',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers:
   { server: 'Cowboy',
     'content-type': 'application/json',
     'access-control-allow-origin': '*',
     'access-control-request-method': '*',
     'access-control-allow-headers': '*',
     'access-control-expose-headers':
      'Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining',
     'cache-control': 'no-cache',
     'x-request-id': '5b349df7-3750-40f1-8d6b-b4b33f057792',
     'x-runtime': '0.009694',
     'strict-transport-security': 'max-age=31536000; includeSubDomains',
     via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
     'accept-ranges': 'bytes, bytes, bytes, bytes',
     'content-length': '55',
     date: 'Sun, 03 Mar 2019 15:44:19 GMT',
     connection: 'close',
     'x-served-by': 'cache-iad2147-IAD, cache-lcy19232-LCY',
     'x-cache': 'MISS, MISS',
     'x-cache-hits': '0, 0',
     'x-timer': 'S1551627859.044306,VS0,VE92',
     vary: 'Origin, Authorization' } }
✖ Unable to connect.```

**Comment by Rawnly** [comment]
Thank you for reporting @jin-ds, in the meantime you can install 3.3.2

**Comment by luceliu** [comment]
Hi same issue here!

node -v
v8.9.4

npm -v
6.8.0

splash -v
3.3.2

OS
Mac OS X 10.13.6

```
OOps! We got an error!

Please report it: on GitHub (https://github.com/splash-cli/splash-cli/issues)

Splash Error:


✖ { HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.data (/usr/local/lib/node_modules/splash-cli/node_modules/got/index.js:386:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HTTPError',
  host: 'api.unsplash.com',
  hostname: 'api.unsplash.com',
  method: 'GET',
  path: '/photos/random?client_id=undefined&count=1&collections=editorial&featured=false',
  protocol: 'https:',
  url: 'https://api.unsplash.com/photos/random?client_id=undefined&count=1&collections=editorial&featured=false',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers: 
   { connection: 'close',
     'content-length': '55',
     server: 'Cowboy',
     'content-type': 'application/json',
     'access-control-allow-origin': '*',
     'access-control-request-method': '*',
     'access-control-allow-headers': '*',
     'access-control-expose-headers': 'Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining',
     'cache-control': 'no-cache',
     'x-request-id': '0e591e47-ae22-4f76-9e1d-06cfb19a17ec',
     'x-runtime': '0.013061',
     'strict-transport-security': 'max-age=31536000; includeSubDomains',
     via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
     'accept-ranges': 'bytes, bytes, bytes, bytes',
     date: 'Fri, 05 Apr 2019 17:02:23 GMT',
     'x-served-by': 'cache-iad2129-IAD, cache-sin18025-SIN',
     'x-cache': 'MISS, MISS',
     'x-cache-hits': '0, 0',
     'x-timer': 'S1554483743.438049,VS0,VE241',
     vary: 'Origin, Authorization' } }
✖ Unable to connect.
```

**Comment by mirkoschubert** [comment]
@Rawnly Same here... Is it fixed in `v3.3.3`? In this case you simply forgot to `npm publish` ;)

**Comment by Rawnly** [comment]
Hi guys, can you please try to manually remove the splash-cli install dir? This because mine on 3.3.2 works pretty fine... However I'll try to figure out what's going on once at all. Thank you for patience

**Comment by toby-daigle** [comment]
Juste tried again with some fresh yarn global.
- Splash-Cli : 3.3.3-1
- Node : 9.10.0
- OS : MacOs Mojave 10.14.3 (18D109)

```
Step 1: yarn global add splash-cli@3.3.3-1
Step 2: splash
...
OOps! We got an error!

Please report it: on GitHub (https://github.com/splash-cli/splash-cli/issues)

Splash Error:


✖ { HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.data (/Users/tdaigle/.config/yarn/global/node_modules/got/index.js:386:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
```

**Comment by Rawnly** [comment]
As you can see below:

https://github.com/splash-cli/splash-cli/blob/5e3ad4a6898626c648409aff6768dd8ebbdc322f/src/extra/Unsplash.js#L14

The key is hardcoded 

https://github.com/splash-cli/splash-cli/blob/5e3ad4a6898626c648409aff6768dd8ebbdc322f/src/extra/config.js#L28-L32

Really don't know what's going on here.. I'll let you know 🤔 

Maybe if you have time and patience try to clone the repo and build/run the master branch.

**Comment by Rawnly** [comment]
I've just pushed a new update, let me know if this is ok for you, btw I've introduced AVA tests and they're fine.

**Comment by toby-daigle** [comment]
Did you publish to npmjs ? 3.3.4-1 does not seems to be listed, hence yarn cannot find the new version

**Comment by Rawnly** [comment]
Nope, i haven't published it yet, i've found a bug inside my test file 😅so if you'd like to test it, just clone the `develop` branch and run the build/start

**Comment by SupperLiang** [comment]
v3.3.3
`splash -day` Unable to get the image

**Comment by SupperLiang** [comment]
OOps! We got an error!

Please report it: on GitHub (https://github.com/splash-cli/splash-cli/issues)

Splash Error:


× { HTTPError: Response code 401 (Unauthorized)
    at stream.catch.then.data (d:\Liang\AppData\Roaming\npm\node_modules\splash-cli\node_modules\got\index.js:386:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'HTTPError',
  host: 'api.unsplash.com',
  hostname: 'api.unsplash.com',
  method: 'GET',
  path: '/photos/random?client_id=undefined&count=1&featured=false',
  protocol: 'https:',
  url:
   'https://api.unsplash.com/photos/random?client_id=undefined&count=1&featured=false',
  statusCode: 401,
  statusMessage: 'Unauthorized',
  headers:
   { server: 'Cowboy',
     'content-type': 'application/json',
     'access-control-allow-origin': '*',
     'access-control-request-method': '*',
     'access-control-allow-headers': '*',
     'access-control-expose-headers':
      'Link,X-Total,X-Per-Page,X-RateLimit-Limit,X-RateLimit-Remaining',
     'cache-control': 'no-cache',
     'x-request-id': '88df1fe4-cafb-4f85-89ba-d425ec7cd5ad',
     'x-runtime': '0.011977',
     'strict-transport-security': 'max-age=31536000; includeSubDomains',
     via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
     'accept-ranges': 'bytes, bytes, bytes, bytes',
     'content-length': '55',
     date: 'Tue, 23 Apr 2019 16:06:15 GMT',
     connection: 'close',
     'x-served-by': 'cache-iad2124-IAD, cache-hnd18749-HND',
     'x-cache': 'MISS, MISS',
     'x-cache-hits': '0, 0',
     'x-timer': 'S1556035576.804340,VS0,VE180',
     vary: 'Origin, Authorization' } }
× Unable to connect.

**Comment by toby-daigle** [comment]
I cloned the repo and checked out `develop`. After `yarn build`, and `yarn start` updated my mac background, as expected.

I'm not sure that we can confirm that it solves the problem because when i checked out v3.3.3, thinking that i could reproduce the Auth Error, it did not happens. Looks like local version is working fine, but the ones from npm is missing some auth keys.

I'll keep searching .. Do not give up Rawnly!

**Comment by Rawnly** [comment]
> Do not give up Rawnly
Never 💪  I just got hired from a company here in my city so I didn't have time to continue working on my OpenSource projects

**Comment by Rawnly** [comment]
I've just released `v3.3.4-2` let me know if this works for you, if it is i'll release a new version with new features as soon as I can 👍

**Comment by SupperLiang** [comment]
let me try

**Comment by SupperLiang** [comment]
Thanks for the big sister, this version is no problem.👍

**Comment by cjcbusatto** [comment]
I installed the version `3.3.4-2` and the issue is fixed for me, thanks!

Just for documentation, my actual configuration is:
OS: **Windows 10**
Node version: `10.15.3`

**Comment by toby-daigle** [comment]
Thanks buddy! v3.3.4-2 is working fine! Good job

**Comment by toby-daigle** [comment]
@Rawnly EDIT - the command `splash` is working fine but i have the same Unauthorized issue with `splash --day`

**Comment by Rawnly** [comment]
Fine, I think that the problem is the lambda behind the —day flag I’ll investigate..

— Federico Vitale
Il 25 apr 2019, 14:27 +0200, Toby Daigle <notifications@github.com>, ha scritto:

**Comment by Rawnly** [comment]
Latest release of the scraper should have fixed this problem

> @Rawnly EDIT - the command `splash` is working fine but i have the same Unauthorized issue with `splash --day`

**Comment by toby-daigle** [comment]
Great! Now it's good!
I tested `splash`, `splash --day`, `splash -u`, `splash -c`, `splash --collection`, `splash -f`
Good job 👍

**Comment by Rawnly** [comment]
Thank you, feel free to re-open the issue if the problem persists!
